-- CREATE SCHEMA `SCHOOLPOPDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- USE SCHOOLPOPDB;

-- CREATE TABLE SCHOOL (
-- 	schoolName		VARCHAR(400) NOT NULL,
-- 	schoolCode		VARCHAR(20) NOT NULL,
-- 	cityProvince	VARCHAR(20) NOT NULL,
-- 	address				VARCHAR(400) NOT NULL
-- );

-- CREATE TABLE POP (
-- 	schoolCode	VARCHAR(20) NOT NULL,
-- 	pop					BIGINT(20) UNSIGNED NOT NULL
-- );

-- ALTER TABLE SCHOOL
-- 	ADD PRIMARY KEY (schoolCode);

-- ALTER TABLE POP
-- 	ADD PRIMARY KEY (schoolCode);




CREATE SCHEMA `EVENT_SCHOOLPOPDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE EVENT_SCHOOLPOPDB;

CREATE TABLE EVENT_SCHOOL (
	schoolName		VARCHAR(400) NOT NULL,
	schoolCode		VARCHAR(20) NOT NULL,
	cityProvince	VARCHAR(20) NOT NULL,
	address				VARCHAR(400) NOT NULL
);

CREATE TABLE EVENT_POP (
	schoolCode	VARCHAR(20) NOT NULL,
	pop					BIGINT(20) UNSIGNED NOT NULL
);

ALTER TABLE EVENT_SCHOOL
	ADD PRIMARY KEY (schoolCode);

ALTER TABLE EVENT_POP
	ADD PRIMARY KEY (schoolCode);
